### ISSUE TITLE
improve the measure up mobile experience

### ISSUE THREAD

**Issue by jerrygitsis** [jerrygitsis/coaltower#20]
the padding is out of whack on the first page of the mobile site, fix it

**Comment by M3ritt** [comment]
Not sure if haml has something like this, since it is a little different than html but for my website I used the following which adjusts the site based on the width of the device being used. 

![mobile](https://user-images.githubusercontent.com/36414900/174929953-8bf947d0-1a5d-4b8f-a340-11913aef316d.png)

**Comment by M3ritt** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1.0">

**Comment by jerrygitsis** [comment]
donezo
